<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit31c8f90abaacda9b913f97331b268a4b
{
    public static $prefixLengthsPsr4 = array (
        'F' => 
        array (
            'FestingerVault\\' => 15,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'FestingerVault\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/includes/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'FestingerVault\\Admin' => __DIR__ . '/../../..' . '/includes/src/Admin.php',
        'FestingerVault\\AutoUpdate' => __DIR__ . '/../../..' . '/includes/src/AutoUpdate.php',
        'FestingerVault\\Constants' => __DIR__ . '/../../..' . '/includes/src/Constants.php',
        'FestingerVault\\Enqueue' => __DIR__ . '/../../..' . '/includes/src/Enqueue.php',
        'FestingerVault\\Helper' => __DIR__ . '/../../..' . '/includes/src/Helper.php',
        'FestingerVault\\Installer' => __DIR__ . '/../../..' . '/includes/src/Installer.php',
        'FestingerVault\\Plugin' => __DIR__ . '/../../..' . '/includes/src/Plugin.php',
        'FestingerVault\\RestAPI' => __DIR__ . '/../../..' . '/includes/src/RestAPI.php',
        'FestingerVault\\Upgrade' => __DIR__ . '/../../..' . '/includes/src/Upgrade.php',
        'FestingerVault\\ViteAssets' => __DIR__ . '/../../..' . '/includes/src/ViteAssets.php',
        'FestingerVault\\api\\ApiBase' => __DIR__ . '/../../..' . '/includes/src/api/ApiBase.php',
        'FestingerVault\\api\\Item' => __DIR__ . '/../../..' . '/includes/src/api/Item.php',
        'FestingerVault\\api\\License' => __DIR__ . '/../../..' . '/includes/src/api/License.php',
        'FestingerVault\\api\\Setting' => __DIR__ . '/../../..' . '/includes/src/api/Setting.php',
        'FestingerVault\\api\\Update' => __DIR__ . '/../../..' . '/includes/src/api/Update.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit31c8f90abaacda9b913f97331b268a4b::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit31c8f90abaacda9b913f97331b268a4b::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit31c8f90abaacda9b913f97331b268a4b::$classMap;

        }, null, ClassLoader::class);
    }
}
